// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/prayer-widget/Fajr.tsx": () => import("../components/mockups/prayer-widget/Fajr.tsx"),
  "./components/mockups/prayer-widget/Isha.tsx": () => import("../components/mockups/prayer-widget/Isha.tsx"),
  "./components/mockups/prayer-widget/Night.tsx": () => import("../components/mockups/prayer-widget/Night.tsx"),
  "./components/mockups/prayer-widget/Noon.tsx": () => import("../components/mockups/prayer-widget/Noon.tsx"),
  "./components/mockups/prayer-widget/Sunrise.tsx": () => import("../components/mockups/prayer-widget/Sunrise.tsx"),
  "./components/mockups/prayer-widget/Sunset.tsx": () => import("../components/mockups/prayer-widget/Sunset.tsx"),
  "./components/mockups/prayer-widget/WidgetBase.tsx": () => import("../components/mockups/prayer-widget/WidgetBase.tsx")
};
